topic_image_height: 
  default: "300px"
  description: "Change the topic list image (thumbnail) section height."
topic_image_fit:
  default: cover
  type: enum
  choices:
    - contain
    - scale-down
    - none
  description: "Select the topic list image (thumbnail) fit. More info: https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit"
topic_image_backdrop:
  type: bool
  default: false
  description: "Add backdrop to topic list image (thumbnail)."
topic_image_backdrop_blur: 
  default: "50px"
  description: "Change the topic_image_backdrop blur size. Set a lower value for less blurred backdrop image."
topic_image_backdrop_brightness: 
  default: "0.65"
  description: "Change the topic_image_backdrop brightness size. Set a lower value for less bright backdrop image."
  right_sidebar_blocks_enabled:
  type: bool
  default: false
  description: "Enabling this will add Right Sidebar Blocks theme component support and replace the original fkb panel with it."

right_sidebar_below_fkb_panel:
  type: bool
  default: false
  description: "Enabling this will add Right Sidebar Blocks theme component below the FKB Panel."
  
custom_sidebar_enabled:
  type: bool
  default: false
  description: "Custom sidebar content for visitor."